### ISSUE TITLE
Plugin does not show any battery information.

### ISSUE THREAD

**Issue by soulawaker** [cmd-johnson/atom-battery-status#14]
I installed it a few minutes ago.

It does not show any info about my laptop battery.

I tried to restart atom but it didn't worked.

I'm using linux and atom 1.13.0 x64.

**Comment by cmd-johnson** [comment]
What distribution are you running and at which version?

Have you tried entering full-screen-mode? It could be that the 'show only while in full-screen'-option is enabled (although that isn't the default).
If that isn't the case, it usually means that no information on the battery could be found. Granted, there should probably be an error message stating that, I'll add that as a new issue.

Confirm that `/sys/class/power_supply/BAT0/` indeed exists on your file-system. If it doesn't, check `/proc/acpi/battery/BAT0/`.

**Comment by soulawaker** [comment]
Did you mean Linux distribution? Elementary OS Loki, based Ubuntu 16.04.
I upgraded basic kernel to 4.9.5 for using Intel Kaby lake CPU.
battery-status version 0.11.1.

I already tried full screen mode with checking its option but it was not worked.

Any error message was not shown.

I confirmed that both `/sys/class/power_supply/BAT0/` and `/proc/acpi/battery/BAT0/` does not exist.

Instead of them, `/sys/class/power_supply/CMB0/` exists. I attach it with snapshot below.

![maybe-battery-status](https://cloud.githubusercontent.com/assets/5372217/22730769/a84635de-ee2b-11e6-872f-c5924fcbd4e3.jpeg)

**Comment by cmd-johnson** [comment]
Hmm, haven't heard of `CMB0` before. But the contents look the same, so this should be a quick fix.

I updated the code in the module responsible for fetching the battery info, a quick re-installation of the plugin should fix your problem.

**Comment by soulawaker** [comment]
Did you mean to re-install same version, battery-status 0.11.1?

I tried uninstalling and re-installing it, but same result, no information.

I've tried one more, uninstalling it, quitting atom, restarting atom, installing it and restarting atom, but same.

**Comment by cmd-johnson** [comment]
Ah, I see, made a typo in my supposed fix.
Well, it *should* work now, uninstalling and reinstalling the plugin should do it.
And yes, the issue is not with this plugin itself, but with a dependency, which is why it is enough to just reinstall the plugin because of the way the dependencies are handled by npm.

**Comment by soulawaker** [comment]
Yeah, it worked!
