### ISSUE TITLE
Status does not update to charging immediately after plug in

### ISSUE THREAD

**Issue by dpkshrma** [cmd-johnson/atom-battery-status#16]
It takes few seconds (about 10 or so) to change icon to charging. Would it be possible to reduce this time? (or maybe show realtime :+1:)

**Comment by cmd-johnson** [comment]
Unfortunately I am yet to find an easy way to get a callback to run as soon as the power supply has been plugged in/out. The way the plugin currently works it is simply querying the power information every `n` seconds, but you can change that interval on the configuration page of the plugin to reduce that time to 1 second (the 'Polling Interval' setting).

**Comment by dpkshrma** [comment]
Understood. That makes sense, unless, the OS has some sort of subscription/push notification service for this, it won't be possible. Thanks for the reply.
