### ISSUE TITLE
Does not seem to work with Atom 1.16.0 on macOS 10.11.6

### ISSUE THREAD

**Issue by zembrowski** [cmd-johnson/atom-battery-status#18]
Hi there,

your package does not seem to work with the current Atom version. At least it does not show any values.

Please take a look at https://github.com/tesseslol/statusbar-battery as it is a fork of your repo and the only big difference seems to be the two first require lines in https://github.com/tesseslol/statusbar-battery/blob/master/lib/battery-status-view.coffee

Best regards,
Krzysztof

**Comment by cmd-johnson** [comment]
Can't reproduce this on Atom 1.16.0 on macOS 10.12.3. Try running `pmset -g batt` and post the output, maybe we can work this out.

**Comment by zembrowski** [comment]
Thanks for your response.

Output of `pmset -g batt` when on battery:
> Now drawing from 'Battery Power'
> -InternalBattery-0 	90%; discharging; 2:42 remaining present: true

and while charging:
> Now drawing from 'AC Power'
> -InternalBattery-0 	88%; charging; 0:35 remaining present: true

**Comment by cmd-johnson** [comment]
Interesting, looks like the battery's ID isn't displayed on your command line output. I'll patch the underlying module that is used to retrieve the battery information to make the ID optional, since it isn't used anywhere anyways.

**Comment by cmd-johnson** [comment]
@zembrowski this should be fixed now, could you try reinstalling the package and give it a try?

**Comment by zembrowski** [comment]
@cmd-johnson Works perfectly 👍 Thanks 😄
