### ISSUE TITLE
Consider using `navigator.getBattery()`

### ISSUE THREAD

**Issue by MatthijsBlom** [cmd-johnson/atom-battery-status#19]
Hi,

Have you considered using `navigator.getBattery()`? [Here](https://googlechrome.github.io/samples/battery-status/) is a demo. A quick test in the Atom console suggests this attribute is supported.

**Comment by cmd-johnson** [comment]
Thank you for that info! I didn't know that API existed.

I added this to the node-power-info package as a fallback for when no native method (like pmset) can be applied and updated the atom package. With this, atom-battery-status now officially supports Windows! :tada:
