### ISSUE TITLE
Add option to only show in full-screen mode

### ISSUE THREAD

**Issue by bean5** [cmd-johnson/atom-battery-status#9]
It is redundant with my OS bar except in full-screen mode.

**Comment by cmd-johnson** [comment]
Good point, I'll look into how to do this as soon as I'm done with my exams!

**Comment by bean5** [comment]
Awesome.

**Comment by bean5** [comment]
Also, I noticed that if you toggle this package on/off a few times, you end up with multiple icons. Probably resolves once you restart Atom, but seems strange. May be indicative of an Atom bug. Feel free to try to replicate and report.

**Comment by cmd-johnson** [comment]
Added in 01300369a74bcd90dcfc622017d450f929d2bbf2

**Comment by bean5** [comment]
Awesome!
